In [33]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.linear_model import LinearRegression
from sklearn.utils import shuffle
from sklearn.model_selection import KFold
from ucimlrepo import fetch_ucirepo 
from operator import itemgetter

Статья про датасет: https://www.sciencedirect.com/science/article/pii/S2352340919306985?via%3Dihub

In [34]:
data = pd.read_csv('./ObesityDataSet.csv')
# переименование для наглядности
data = data.rename(columns={'FAVC': 'high_caloric_food_frequent', 'FCVC': 'vegetables_frequency', 'NCP': 'meals_a_day', 'CAEC': 'snacks', 'SCC': 'monitor_calories', 'FAF': 'days_of_physical_activity', 'TUE': 'hours_on_tech_devices', 'CALC': 'alcohol_frequency'})
data

,Gender,Age,Height,Weight,family_history_with_overweight,high_caloric_food_frequent,vegetables_frequency,meals_a_day,snacks,SMOKE,CH2O,monitor_calories,days_of_physical_activity,hours_on_tech_devices,alcohol_frequency,MTRANS,NObeyesdad
0,Female,21.000000,1.620000,64.000000,yes,no,2.0,3.0,Sometimes,no,2.000000,no,0.000000,1.000000,no,Public_Transportation,Normal_Weight
1,Female,21.000000,1.520000,56.000000,yes,no,3.0,3.0,Sometimes,yes,3.000000,yes,3.000000,0.000000,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.000000,1.800000,77.000000,yes,no,2.0,3.0,Sometimes,no,2.000000,no,2.000000,1.000000,Frequently,Public_Transportation,Normal_Weight
3,Male,27.000000,1.800000,87.000000,no,no,3.0,3.0,Sometimes,no,2.000000,no,2.000000,0.000000,Frequently,Walking,Overweight_Level_I
4,Male,22.000000,1.780000,89.800000,no,no,2.0,1.0,Sometimes,no,2.000000,no,0.000000,0.000000,Sometimes,Public_Transportation,Overweight_Level_II
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,Female,20.976842,1.710730,131.408528,yes,yes,3.0,3.0,Sometimes,no,1.728139,no,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III
2107,Female,21.982942,1.748584,133.742943,yes,yes,3.0,3.0,Sometimes,no,2.005130,no,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III
2108,Female,22.524036,1.752206,133.689352,yes,yes,3.0,3.0,Sometimes,no,2.054193,no,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III
2109,Female,24.361936,1.739450,133.346641,yes,yes,3.0,3.0,Sometimes,no,2.852339,no,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III
2110,Female,23.664709,1.738836,133.472641,yes,yes,3.0,3.0,Sometimes,no,2.863513,no,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III

Берём все признаки, кроме определяемых (вес)

In [35]:
X = data.drop(['NObeyesdad', 'Weight'], axis=1)
X

,Gender,Age,Height,family_history_with_overweight,high_caloric_food_frequent,vegetables_frequency,meals_a_day,snacks,SMOKE,CH2O,monitor_calories,days_of_physical_activity,hours_on_tech_devices,alcohol_frequency,MTRANS
0,Female,21.000000,1.620000,yes,no,2.0,3.0,Sometimes,no,2.000000,no,0.000000,1.000000,no,Public_Transportation
1,Female,21.000000,1.520000,yes,no,3.0,3.0,Sometimes,yes,3.000000,yes,3.000000,0.000000,Sometimes,Public_Transportation
2,Male,23.000000,1.800000,yes,no,2.0,3.0,Sometimes,no,2.000000,no,2.000000,1.000000,Frequently,Public_Transportation
3,Male,27.000000,1.800000,no,no,3.0,3.0,Sometimes,no,2.000000,no,2.000000,0.000000,Frequently,Walking
4,Male,22.000000,1.780000,no,no,2.0,1.0,Sometimes,no,2.000000,no,0.000000,0.000000,Sometimes,Public_Transportation
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,Female,20.976842,1.710730,yes,yes,3.0,3.0,Sometimes,no,1.728139,no,1.676269,0.906247,Sometimes,Public_Transportation
2107,Female,21.982942,1.748584,yes,yes,3.0,3.0,Sometimes,no,2.005130,no,1.341390,0.599270,Sometimes,Public_Transportation
2108,Female,22.524036,1.752206,yes,yes,3.0,3.0,Sometimes,no,2.054193,no,1.414209,0.646288,Sometimes,Public_Transportation
2109,Female,24.361936,1.739450,yes,yes,3.0,3.0,Sometimes,no,2.852339,no,1.139107,0.586035,Sometimes,Public_Transportation
2110,Female,23.664709,1.738836,yes,yes,3.0,3.0,Sometimes,no,2.863513,no,1.026452,0.714137,Sometimes,Public_Transportation

Будем пытаться посчитать вес (не степень ожирения)

In [36]:
Y = data['Weight']
Y

0        64.000000
1        56.000000
2        77.000000
3        87.000000
4        89.800000
           ...
2106    131.408528
2107    133.742943
2108    133.689352
2109    133.346641
2110    133.472641
Name: Weight, Length: 2111, dtype: float64

In [37]:
X, Y = shuffle(X, Y, random_state=0)

## 1. Линейная регрессия

In [42]:
X_numeric = X[['Age', 'Height', 'vegetables_frequency', 'meals_a_day', 'CH2O', 'days_of_physical_activity', 'hours_on_tech_devices']]
X_numeric

,Age,Height,vegetables_frequency,meals_a_day,CH2O,days_of_physical_activity,hours_on_tech_devices
1730,30.595632,1.910672,2.497548,3.000000,1.362583,1.144076,0.173232
259,18.000000,1.670000,1.000000,3.000000,1.000000,0.000000,1.000000
966,29.153907,1.773656,1.595746,3.618722,1.274389,1.504003,0.370067
1911,18.314593,1.745602,3.000000,3.000000,2.923792,1.536555,0.625350
1815,18.771001,1.746652,3.000000,3.000000,2.869234,1.465931,0.627886
...,...,...,...,...,...,...,...
1033,19.671876,1.699474,1.925064,2.358298,2.774043,0.000000,0.133566
1731,30.554956,1.779136,2.671238,3.000000,2.145368,0.882709,0.593917
763,21.000000,1.620000,2.000000,1.000000,3.000000,1.000000,0.000000
835,29.320380,1.642506,2.366949,3.000000,1.926577,1.581242,0.000000
1653,24.417552,1.774775,2.233720,2.993634,2.028368,0.863158,0.449886

In [43]:
clf = LinearRegression()
clf.fit(X_numeric, Y)

LinearRegression()

In [ ]:
clf.